version: '3.3'
services:
 combiner:
  image: "scaleoutsystems/fedn-combiner:develop"
  environment:
   - PYTHONUNBUFFERED=0
   - GET_HOSTS_FROM=dns
  extra_hosts:
    reducer: 130.238.29.222
  build:
   context: /home/ubuntu/fedn
   dockerfile: /home/ubuntu/fedn/components/combiner/Dockerfile
  working_dir: /app/client
  command: sh -c "sleep 5 && fedn run combiner -in ./config/settings-combiner.yaml"
  volumes:
   - /home/ubuntu/fedn/config:/app/client/config
   - /home/ubuntu/tmp/c1-models:/tmp/models
  ports:
   - 12080:12080
