version: '3.3'
services:
   reducer:
     extra_hosts:
        combiner-aws-ireland: 3.249.15.209
        combiner-aws-us-east: 54.242.196.73
        combiner-aws-stockholm: 13.53.197.49
        combiner-aws-frankfurt: 18.159.50.207
